// Helpers for resolving the sender label of an order_form_message,
// independent of the perspective (admin vs. customer).

export type SenderContext = "admin" | "customer";

interface SubmissionLike {
  submitter_name?: string | null;
  submitter_email?: string | null;
  notification_recipient_name?: string | null;
  notification_recipient_email?: string | null;
}

interface MessageLike {
  sender_type?: string | null;
  sender_name?: string | null;
  sender_user_id?: string | null;
  source?: string | null;
  message_type?: string | null;
  body?: string | null;
}

const Lier VPS_NAME_HINTS = [
  "mcs service",
  "mcs ressurs",
  "mcs postkontor",
  "postkontor",
  "no-reply",
  "noreply",
  "automatisk",
  "system",
];

function normalize(value?: string | null): string {
  return (value || "").trim().toLowerCase();
}

function looksLikeInternalSender(name?: string | null): boolean {
  const n = normalize(name);
  if (!n) return false;
  return Lier VPS_NAME_HINTS.some((hint) => n.includes(hint));
}

/**
 * Effective category of a message, regardless of how it was stored.
 *  - "system"   : autogenerated (e.g. "Ny bestilling: BST-...") or no real human author
 *  - "internal" : from an Lier VPS user (admin role or service mailbox loopback)
 *  - "customer" : from the actual submitter / bestiller
 */
export function resolveSenderKind(
  message: MessageLike,
  submission?: SubmissionLike | null,
): "system" | "internal" | "customer" {
  const type = normalize(message.sender_type);
  const name = message.sender_name || "";

  if (type === "system") return "system";

  // Loopback case: stored as "customer" but actually from Lier VPS service mailbox.
  // Treat such senders as internal so we never show them as "Du".
  if (type === "customer" && looksLikeInternalSender(name)) {
    return "internal";
  }

  if (type === "admin" || type === "internal" || message.sender_user_id) {
    return "internal";
  }

  if (type === "customer") {
    // Real customer message — verify against submitter when we have it
    if (submission?.submitter_name) {
      if (normalize(name) === normalize(submission.submitter_name)) return "customer";
    }
    return "customer";
  }

  // Defensive fallback
  return looksLikeInternalSender(name) ? "internal" : "customer";
}

/**
 * Returns the label to render for the sender of a message.
 * Always avoids a misleading "Du" when the message is not actually from
 * the current viewer.
 */
export function getMessageSenderLabel(
  message: MessageLike,
  submission: SubmissionLike | null | undefined,
  context: SenderContext,
): string {
  const kind = resolveSenderKind(message, submission);
  const name = (message.sender_name || "").trim();

  if (kind === "system") {
    return "Automatisk melding";
  }

  if (kind === "internal") {
    if (context === "customer") {
      // Don't expose loopback / mailbox names like "Lier VPS - Postkontor"
      if (looksLikeInternalSender(name)) return "Lier VPS";
      return name || "Lier VPS";
    }
    return name || "Lier VPS";
  }

  // Customer
  if (context === "customer") {
    // Only show "Du" when this really is the same submitter
    const submitter = submission?.submitter_name || "";
    if (submitter && normalize(submitter) === normalize(name)) return "Du";
    return name || submitter || "Bestiller";
  }
  return name || submission?.submitter_name || "Bestiller";
}
