-- 1. Drop anon write policies on order_form_messages — public tracking
-- inserts must now go through the order-message-public-send edge function.
DROP POLICY IF EXISTS "Anon can insert customer replies" ON public.order_form_messages;
DROP POLICY IF EXISTS "Anon can mark messages as replied" ON public.order_form_messages;

-- Re-add a narrow UPDATE policy so customers can still mark a request_info
-- question as replied (replied_at) from the public page.
CREATE POLICY "Anon can mark request_info as replied"
ON public.order_form_messages
FOR UPDATE
TO anon
USING (
  public.submission_has_tracking_token(submission_id)
  AND message_type = 'request_info'
)
WITH CHECK (
  public.submission_has_tracking_token(submission_id)
);

-- 2. Drop anon insert on legacy comments — same reason.
DROP POLICY IF EXISTS anon_insert_customer_reply ON public.order_form_comments;

-- 3. Backfill: customer -> system (autogenerated mailbox messages)
UPDATE public.order_form_messages
SET sender_type = 'system',
    sender_name = 'Automatisk melding',
    source = COALESCE(source, 'system')
WHERE sender_type = 'customer'
  AND (
    lower(coalesce(sender_name,'')) LIKE '%postkontor%'
    OR lower(coalesce(sender_name,'')) LIKE '%no-reply%'
    OR lower(coalesce(sender_name,'')) LIKE '%noreply%'
    OR lower(coalesce(sender_name,'')) LIKE 'mcs service - postkontor%'
    OR lower(coalesce(sender_name,'')) LIKE '%automatisk%'
  );

-- 4. Backfill: customer -> internal (sent by an internal user via public page)
WITH internal_users AS (
  SELECT DISTINCT ua.auth_user_id AS uid, p.full_name, p.email
  FROM public.user_accounts ua
  JOIN public.people p ON p.id = ua.person_id
  WHERE ua.is_active = true
    AND ua.auth_user_id IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.user_memberships um
      WHERE um.user_id = ua.auth_user_id AND um.is_active = true
    )
)
UPDATE public.order_form_messages m
SET sender_type = 'internal',
    sender_user_id = COALESCE(m.sender_user_id, iu.uid),
    sender_name = COALESCE(NULLIF(m.sender_name,''), iu.full_name),
    source = 'public_tracking_internal'
FROM internal_users iu
WHERE m.sender_type = 'customer'
  AND m.sender_user_id IS NULL
  AND iu.email IS NOT NULL
  AND lower(iu.full_name) = lower(coalesce(m.sender_name,''))
  AND iu.full_name IS NOT NULL
  AND length(iu.full_name) > 2;